Repository oidc-wp/openid-connect-generic, pull requests merged in 2022-02, with the labels that each got.

#369 Development Environment & Dependecies Updates
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/library-scripts/common-debian.sh
  .devcontainer/library-scripts/docker-in-docker-debian.sh
  .github/workflows/linting.yml
  .github/workflows/pr-unit-testing.yml
  .github/workflows/static-analysis.yml
  .github/workflows/unit-testing.yml
  .gitpod.yml
  .vscode/tasks.json
  .wp-env.json
  composer.json
  composer.lock
  docker-compose.wp-env.yml
  docker-compose.yml
  includes/openid-connect-generic-client-wrapper.php
  includes/openid-connect-generic-settings-page.php
  openid-connect-generic.php
  package-lock.json
  package.json
  phpcs.xml.dist
  phpstan.neon.dist
  tools/docker/composer/Dockerfile
Labels: enhancement, refactor

#364 Multisite/network configurations use your current blog as the default…
  includes/openid-connect-generic-client-wrapper.php
Labels: bug, status: approved

#256 added define config with OIDC_LOGIN_TYPE and OIDC_CLIENT_SCOPE
  HOWTO.md
  includes/openid-connect-generic-option-settings.php
  includes/openid-connect-generic-settings-page.php
  openid-connect-generic.php
  tests/phpstan-bootstrap.php
Labels: enhancement, status: approved

#255 Aggregated claims
  includes/openid-connect-generic-client-wrapper.php
Labels: enhancement, status: needs review

#190 Implement singleton pattern for OpenID_Connect_Generic class
  includes/functions.php
  openid-connect-generic.php
Labels: enhancement, status: approved, status: needs changelog, status: needs docs

#380 Updates NPM Modules & Changes Plugin Instance Visibility
  .nvmrc
  .wp-env.json
  openid-connect-generic.php
  package-lock.json
  package.json
Labels: refactor, dependencies

#337 Fix #178 : update user meta after refresh
  includes/openid-connect-generic-client-wrapper.php
Labels: enhancement, status: needs review
