Repository oidc-wp/openid-connect-generic, pull requests merged in 2022-03, with the labels that each got.

#228 Add openid-connect-generic-session-expired action on session expiry before logout
  includes/openid-connect-generic-client-wrapper.php
Labels: enhancement, status: approved, status: needs changelog, status: needs docs

#345 Only load admin CSS when showing settings page
  includes/openid-connect-generic-settings-page.php
  openid-connect-generic.php
Labels: enhancement, status: approved

#338 Refresh user claim
  includes/openid-connect-generic-client-wrapper.php
  openid-connect-generic.php
Labels: enhancement, status: approved

#388 Acr value support
  includes/openid-connect-generic-client-wrapper.php
  includes/openid-connect-generic-client.php
  includes/openid-connect-generic-option-settings.php
  includes/openid-connect-generic-settings-page.php
  openid-connect-generic.php
Labels: enhancement, status: needs review

#389 Refactors new ACR Handling Code for Better Code Quality
  includes/openid-connect-generic-client-wrapper.php
  includes/openid-connect-generic-client.php
  includes/openid-connect-generic-settings-page.php
Labels: status: approved

#390 Fixes 3.8.0 Regression for User Creation Failure When No Nickname
  .nvmrc
  includes/openid-connect-generic-client-wrapper.php
Labels: bug

#335 Fixes QS not being added to the redirect URL
  includes/openid-connect-generic-client-wrapper.php
Labels: bug, status: approved

#392 Fixes User Linking & Creation Issues
  includes/openid-connect-generic-client-wrapper.php
  includes/openid-connect-generic-settings-page.php
Labels: status: needs review

#393 Dependabot Security Related Fixes & Refactoring
  .github/workflows/i18n.yml
  .github/workflows/pr-unit-testing.yml
  .github/workflows/release.yml
  .github/workflows/unit-testing.yml
  composer.json
  package-lock.json
  package.json
Labels: refactor, dependencies

#396 Refactors Callable Refresh User Claims Function & Action
  includes/functions.php
  includes/openid-connect-generic-client-wrapper.php
  openid-connect-generic.php
Labels: refactor

#394 3.9.0 Feature & Bugfix Release
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/library-scripts/common-debian.sh
  .devcontainer/library-scripts/docker-in-docker-debian.sh
  .github/workflows/i18n.yml
  .github/workflows/linting.yml
  .github/workflows/pr-unit-testing.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/unit-testing.yml
  .gitpod.yml
  .nvmrc
  .vscode/tasks.json
  .wp-env.json
  CHANGELOG.md
  HOWTO.md
  README.md
  composer.json
  composer.lock
  docker-compose.wp-env.yml
  docker-compose.yml
  includes/functions.php
  includes/openid-connect-generic-client-wrapper.php
  includes/openid-connect-generic-client.php
  includes/openid-connect-generic-option-settings.php
  includes/openid-connect-generic-settings-page.php
  languages/openid-connect-generic.pot
  openid-connect-generic.php
  package-lock.json
  package.json
  phpcs.xml.dist
  phpstan.neon.dist
  readme.txt
  tests/phpstan-bootstrap.php
  tools/docker/composer/Dockerfile
Labels: release
